### ISSUE TITLE
Voting system

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-node#13]
Not sure if this is the right place to post but I think you should change how the voting system works. Able to add only 1 delegate is very frustrating. What if I have 100k ARK and want to split them between 10 delegates? I should create 10 accounts and remember 10 passphrases??? Don't think so.

I believe the right approach is to be able to add as many delegates as you want and just assign a % weight of your balance to every delegate. This way you could add 10 delegates, assign 10% weight to everyone and that's it, every delegates will receive 10k voting power. No need to create multiple accounts.

**Comment by fix** [comment]
check this:
https://github.com/ArkEcosystem/AIPs/blob/master/AIPS/aip-2.md

and comments are here:
https://github.com/ArkEcosystem/AIPs/issues/1

Keep in mind that when BIP32 is available (it is already but not binded in UI), you can handle 100s of accounts with only 1 master seed passphrase

Fix

**Comment by fix** [comment]
On side note there are many reason to keep it simple as it is now as well. Most holders will find complicated process to manage multiple votes. We want to keep it simple of the man in the street:
- vote is important for securing
- you can grab some ark by voting pools

**Comment by fix** [comment]
closing moving the discussion to AIP repo
