### ISSUE TITLE
error: - {"message":"Maximum number of 1 votes exceeded (50 too many)"

### ISSUE THREAD

**Issue by pconstr** [ArkEcosystem/ark-node#14]
I get this when starting a private network on an empty database:

```node app.js -c tasks/config.json -g tasks/genesisBlock.json```

it happens after applying a number of transactions.

**Comment by pconstr** [comment]
happens both running the current HEAD and 0.3.0

**Comment by fix** [comment]
Hi, sorry about this right now only "mainnet" branch is in functionning state, I am working to make master and testnet in functionning so we can relaunch testnet. A few days of patience is needed.

Your error is due to the fact that there is only 1 vote allowed per account and the genesis block is not compatible (ie voting with 51 votes) with last version of code.

**Comment by pconstr** [comment]
Thanks @fix
I've found I can run `development`privately by setting `maximumVotes` to `51` in `helpers/constants.js`. I can't tell what unintended consequences might bring, but it's at least enough to experiment a bit now.
Is there something I can do to help make `master` and `testnet` work again?
I'm comfortable with node and know a bit about the lisk codebase.

**Comment by fix** [comment]
yes this is harmless (ie it should work as intended).
For testnet, i am pushing this week new version so it should work back again...

**Comment by pconstr** [comment]
cool, thanks

**Comment by boldninja** [comment]
@pconstr also don't forget that we have GitHub bounty so if you are familiar with the code you won't have any problem getting in this : https://blog.ark.io/200-000-ark-bounty-for-developers-in-the-1st-year-76aa44304012 .

**Comment by faustbrian** [comment]
As Core 2.0 is under development we will close all the PRs and Issues regarding Core 1.0 and only handle critical issues if any come up.
