### ISSUE TITLE
Node Status is broken 

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/ark-node#15]
![status](https://cloud.githubusercontent.com/assets/4367481/26166468/eb842608-3b33-11e7-93bd-c930d6185fbb.PNG)

I did set my delegate correctly and it is forging. But the Status window does not show it.

**Comment by tharude** [comment]
How about changing the current running address with the address of your delegate as an example or just wait a bit for a reseted version to be uploaded.

**Comment by Jarunik** [comment]
Thanks. Could fix it manually and tested new version. Works fine with that one now.
