### ISSUE TITLE
Feature Request: Automatic failover for delegate nodes

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/ark-node#16]
It looks like we can already run two nodes which secrets plugged in. It is as simple as stopping forging node and restarting backup node.

It would be cool if we can add a failover functionality in order that backup relay nodes would automatically pickup forging if main delegate node fails.

**Comment by Isabello** [comment]
I don't think its possible since forging is enabled on startup in ARK. It
would require some kind of heartbeat connection between the nodes and new
logic maybe ;)

**Comment by faustbrian** [comment]
As Core 2.0 is under development we will close all the PRs and Issues regarding Core 1.0 and only handle critical issues if any come up.
