### ISSUE TITLE
New nodes unable to sync with testnet

### ISSUE THREAD

**Issue by dafty235** [ArkEcosystem/ark-node#2]
It seems that new nodes are unable to initially sync with the testnet.

This can be reproduced by starting a new node from scratch and installing the build script from https://ark.io/installARK.sh. This doesn't seem to affect nodes which were already syncing 3 days ago.

When starting the node, an UnhandledPromiseRejectionWarning exception is thrown, and the node hangs indefinitely.

![image](https://cloud.githubusercontent.com/assets/24987593/21749320/80659c8a-d594-11e6-82c0-8ad7d161b476.png)

Some simple debugging of app.js shows that the exception is thrown while requiring ark.js in the logic/blocks.js file.

![image](https://cloud.githubusercontent.com/assets/24987593/21750226/60e5e646-d5a6-11e6-9e82-844d9c931b9e.png)

I wonder if this is a problem when importing the genesis block, or if the change to addressing has caused nodes without any blocks to stop importing blocks returned from the network.

**Comment by 4miners** [comment]
@dafty235 Why close?

**Comment by dafty235** [comment]
Fixed in https://github.com/ArkEcosystem/ark-node/commit/4534493d77f647eba4ead7d43f4cf9a019b8f465

**Comment by 4miners** [comment]
Ok, thanks.
