### ISSUE TITLE
Add system tests that check API response structure

### ISSUE THREAD

**Issue by bradyo** [ArkEcosystem/ark-node#20]
We should add system tests that check API response structure to ensure we don't make "breaking" changes on the API contract. 

Breaking API changes might include:
- renaming a property
- removing a property
- changing the type of a property
- moving the property to a different nesting level
- making a required property optional

We should add this in a way that makes it easy to add the test for any endpoint that returns data. A simple way to verify the structure might be to use json schema validation like so:

```js
var expectedResponseSchema = {
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "blockId": {
            "type": "string"
        }
    },
    "required": ["id", "blockId"]
}
var result = client.get("/transactions/get?id=12345");
jsonSchemaValidator.validate(result, expectedResponseSchema);
```

**Comment by fix** [comment]
i like it.

as for structuration, please see teh way i validate peer communication
- https://github.com/ArkEcosystem/ark-node/blob/development/schema/api.peer.js
- https://github.com/ArkEcosystem/ark-node/blob/development/schema/api.public.js

**Comment by faustbrian** [comment]
As Core 2.0 is under development we will close all the PRs and Issues regarding Core 1.0 and only handle critical issues if any come up.
