### ISSUE TITLE
ARKcommander.sh fails if another file/folder with ark-node exists on the system

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/ark-node#24]
# Looking for ark-node installations and performing actions
        arkdir=`locate -b ark-node`

This locate might return more than one folder and ARKcommander does not work anymore.

Example:
jarunik@vps416986:~$ locate -b ark-node
/home/jarunik/ark-node
/home/jarunik/work/src/github.com/jarunik/ark-go/cmd/arkgoserver/log/go**ark-node**.log

You will get a ARKcommander.sh: line 1078: [: /home/jarunik/ark-node: binary operator expected error and you can't start the node.

Most likely the search for ark-node should be a bit more restrictive.

**Comment by alexbarnsley** [comment]
@Jarunik I just tested this on ARKcommander.sh and it works. Is it possible you have an old version? Looking at the line you're referencing, I see it specifically checking for the backslash (\\):

```
arkdir=`locate -b "\ark-node"`
```

**Comment by boldninja** [comment]
I have made changes already and reuploaded both commanders as soon as it was reported to me.

**Comment by alexbarnsley** [comment]
Is it worth closing in that case?

**Comment by boldninja** [comment]
Sure @Jarunik can close it.

**Comment by Jarunik** [comment]
Thanks :-)
