### ISSUE TITLE
Ideas about /api/transactions refactoring

### ISSUE THREAD

**Issue by biolypl** [ArkEcosystem/ark-node#25]
I propose add this parametrs for /api/transactions:
1.  _minAmount, maxAmount_, to set transactions amount
2. _type_, to choose type of transaction
3. _smart bridge_, get transaction with specify smart bridge value

**Comment by faustbrian** [comment]
As Core 2.0 is under development we will close all the PRs and Issues regarding Core 1.0 and only handle critical issues if any come up.
