### ISSUE TITLE
Genesis block generation scripts missing ed.js dependency

### ISSUE THREAD

**Issue by dafty** [ArkEcosystem/ark-node#28]
[createGenesisBlock.js](https://github.com/ArkEcosystem/ark-node/blob/mainnet/tasks/createGenesisBlock.js#L9)
[createGenesisBlockFromAccounts.js](https://github.com/ArkEcosystem/ark-node/blob/mainnet/tasks/createGenesisBlockFromAccounts.js#L9)

Change signing to use ark-js?

**Comment by fix** [comment]
yes

**Comment by faustbrian** [comment]
As Core 2.0 is under development we will close all the PRs and Issues regarding Core 1.0 and only handle critical issues if any come up.
