### ISSUE TITLE
Peers API ignore limit/offset

### ISSUE THREAD

**Issue by 4miners** [ArkEcosystem/ark-node#3]
Example: http://178.32.203.37:4000/api/peers?limit=1&offset=10000

**Comment by fix** [comment]
yes actually, i disabled it, and will likely obsfucate more the details of peers being sent, to prevent from attacking the network.

Rationale here is the following: This function is for interconnecting full nodes and for lite client connection. The point is to provide a reliable entry point into the ark network, not provide a list of nodes for network analysis. To perform network analysis, one should poll a few different peers instead.

**Comment by fix** [comment]
Leaving issue open for more discussions

**Comment by faustbrian** [comment]
As Core 2.0 is under development we will close all the PRs and Issues regarding Core 1.0 and only handle critical issues if any come up.
