### ISSUE TITLE
Integer - String issue when calling  /peer/blocks/?lastBlockHeight

### ISSUE THREAD

**Issue by kristjank** [ArkEcosystem/ark-node#30]
A different responses for block... i.e. calling /peer/blocks/?lastBlockHeight=1505795 I get
`"totalAmount": "0",
"totalFee": "0",
"reward": "200000000",`

when getting from other nodes using POST /peer/blocks the values are in int. And according to schema INTEGER is OK.
`"totalAmount": 0,
"totalFee": 0,
"reward": 200000000,`

Suggesting to adjust this in next release.

**Comment by alexbarnsley** [comment]
Hi, @kristjank, was just looking into this for you. From what I can see, posting to /peer/blocks returns JSON with the blockId, not the formatted data you gave above. See [this line](https://github.com/ArkEcosystem/ark-node/blob/c1df3762a4301deab54f7ab0f7935a7975497cd5/modules/transport.js#L208) to get an idea of what is being returned. Thanks

**Comment by alexbarnsley** [comment]
Following on from my comment, I think I missed some out. I just wanted to confirm you are definitely posting to /peer/blocks, and whether you'd be able to provide an example response?

**Comment by kristjank** [comment]
Hi Alex, this error is on the node2node communication - not the client.
I am implementing alternative implementation of the ark-node and I noticed the difference of response.  It is not a big deal, unless you prepare a structure to store block data / then you must handle the different responses...

So we talked with  @fix to add this note... to not forget about this

**Comment by kristjank** [comment]
one is receiving blocks from other nodes (when your node is in sync...)
and another is requesting blocks from other nodes - getting up to the same block height

and the answers (JSON structures) in this answers are different...

**Comment by fix** [comment]
yes issue is located here: https://github.com/ArkEcosystem/ark-node/blob/development/modules/transport.js#L144

for some reason the database query does not yield the right json formatting. I did not want to add a loop to reformat properly, because it could be costly for the node...

**Comment by fix** [comment]
and schema is bigint, so maybe the lib is taking bigint as string https://github.com/ArkEcosystem/ark-node/blob/development/sql/migrations/20160723182900_createSchema.sql#L22

**Comment by alexbarnsley** [comment]
You were right @fix. There are issues casting though. Please take a look at the PR description. It may be a string is acceptable.

**Comment by alexbarnsley** [comment]
Or do you think changing the schema type would be better, to a standard int? Does it need to be a bigint?

**Comment by fix** [comment]
well:
- bigint is needed (int is not enough to encode 1M arks for instance).
- in next version i will get rid off json format for data exchange so this won't be an issue anymore

**Comment by alexbarnsley** [comment]
@fix absolutely. That's why I questioned it when I created the PR. Yeah that makes sense. Is it worth me closing the PR and you closing the issue as it technically can't be fixed due to using JSON? With the view of using data exchange in the next version?

**Comment by fix** [comment]
yes please close PR, i won't merge it, but you get +5 arks for coming with a solutino

**Comment by alexbarnsley** [comment]
thanks @fix! I see you've already closed the PR. It's a shame js doesn't support 64bit int. maybe one day!

**Comment by faustbrian** [comment]
As Core 2.0 is under development we will close all the PRs and Issues regarding Core 1.0 and only handle critical issues if any come up.
