### ISSUE TITLE
Idea about /api/accounts?address= refactoring

### ISSUE THREAD

**Issue by biolypl** [ArkEcosystem/ark-node#37]
For now this query for correct data return:  `success,address,unconfirmedBalance,balance,publicKey,unconfirmedSignature,secondSignature, secondPublicKey, multisignatures, u_multisignatures`

My idea is to add for this result also _delegate array_ for which this account vote. I think it isn't problem as long as one account is able to vote for one delegate.

**Comment by faustbrian** [comment]
As Core 2.0 is under development we will close all the PRs and Issues regarding Core 1.0 and only handle critical issues if any come up.
