### ISSUE TITLE
Wrong network showing up when nodes does not drop database after nethash update

### ISSUE THREAD

**Issue by fix** [ArkEcosystem/ark-node#4]
This is protocol level issue:
- fast fix: prevent from node to start if block height 1 in db is different from genesisBlock.json
- full fix: upgrade protocol, for instance signing all blocks including nethash. Other protocol upgrades possible. Good for AIP proposal

**Comment by faustbrian** [comment]
As Core 2.0 is under development we will close all the PRs and Issues regarding Core 1.0 and only handle critical issues if any come up.
