### ISSUE TITLE
round boundaries stress the server

### ISSUE THREAD

**Issue by ghost** [ArkEcosystem/ark-node#46]
I noticed that the majority of the "Blockchain not ready to receive block" messages happens at, or very close to, block numbers that can be divided by 51. That message brings the weaker of my servers to it's knees several times a day, so I have to restart app.js. Just as heads up that there seems to be a point of heavy load on the servers at the round turnover.

**Comment by ghost** [comment]
the query that updates the votes between rounds, takes 7.5 seconds on my weakest server. Seems to be the cause. Need a faster server lol.

**Comment by faustbrian** [comment]
As Core 2.0 is under development we will close all the PRs and Issues regarding Core 1.0 and only handle critical issues if any come up.
