### ISSUE TITLE
Remove success: property in favour of status codes

### ISSUE THREAD

**Issue by dafty** [ArkEcosystem/ark-node#48]
Having a `success: false` property in the response is not RESTful.

It would be faster (less bandwidth, response parsing) and more compliant (if we were aiming for a REST interface) to use standard HTTP status codes with an optional error in some cases, 400, 404, etc.

**Comment by faustbrian** [comment]
As Core 2.0 is under development we will close all the PRs and Issues regarding Core 1.0 and only handle critical issues if any come up.
