### ISSUE TITLE
Lost coins

### ISSUE THREAD

**Issue by zgreat** [ArkEcosystem/ark-node#57]
Few months back I bought a small amount of coins (107) from bittrex now I find that my wallet has zero balance and the address is completely different. 
Can anything be done?

Address: AN5JpGaKt1eiDFsNS6Tz9ctViymoc81XJ2

**Comment by luciorubeens** [comment]
Hi @Mast3rMind, where did you check your balance? Is not zero in the explorer: https://explorer.dafty.net/address/AN5JpGaKt1eiDFsNS6Tz9ctViymoc81XJ2

**Comment by zgreat** [comment]
@luciorubeens I'm aware but the address is no longer in my wallet. It's hard to explain. The word list I have generates completely different address.

I was using the Ark Desktop client on Windows

I consider them gone closing this
