### ISSUE TITLE
security issues regarding adhoc queries from middle tier

### ISSUE THREAD

**Issue by ReinsBrain** [ArkEcosystem/ark-node#58]
https://github.com/ArkEcosystem/ark-node/blob/447817b22f06c447bcc95358247e123da850c815/sql/blocks.js#L16

It would be better to wrap many of these queries into functions with SECURITY DEFINER so that direct table access can be locked down to only the super user. Those functions can move to migrations folder along with table and view creations. I would be happy to fork and pull-request that effort if it were welcome. I'd also semantically version the migrations folder to simplify updates. Please let me know :)

**Comment by faustbrian** [comment]
As Core 2.0 is under development we will close all the PRs and Issues regarding Core 1.0 and only handle critical issues if any come up.
