### ISSUE TITLE
A error. Cannot get data from peers 

### ISSUE THREAD

**Issue by bicaso2013** [ArkEcosystem/ark-node#60]
[dbg] 2018-03-05 09:27:58 | Removing from memory blockchain blocks with height under - -199
[dbg] 2018-03-05 09:27:59 | Blockchain state - {"date":"2018-03-05T09:24:18.921Z","secondsAgo":221,"stale":true,"rebuild":false,"height":1}
[trc] 2018-03-05 09:28:02 | requestFromPeer - {"ip":"116.85.49.217","port":4100,"errors":31,"status":"ETIMEOUT","delay":0}
[trc] 2018-03-05 09:28:07 | requestFromPeer - {"ip":"47.91.218.198","port":4100,"errors":32,"status":"ETIMEOUT","delay":0}
[dbg] 2018-03-05 09:28:07 | Blockchain state - {"date":"2018-03-05T09:24:18.921Z","secondsAgo":229,"stale":true,"rebuild":false,"height":1}
[dbg] 2018-03-05 09:28:08 | Removing from memory blockchain blocks with height under - -199
[trc] 2018-03-05 09:28:12 | requestFromPeer - {"ip":"47.91.218.198","port":4100,"errors":33,"status":"ETIMEOUT","delay":0}
[dbg] 2018-03-05 09:28:15 | Blockchain state - {"date":"2018-03-05T09:24:18.921Z","secondsAgo":237,"stale":true,"rebuild":false,"height":1}
[trc] 2018-03-05 09:28:17 | requestFromPeer - {"ip":"47.91.218.198","port":4100,"errors":34,"status":"ETIMEOUT","delay":0}
[dbg] 2018-03-05 09:28:18 | Removing from memory blockchain blocks with height under - -199
[trc] 2018-03-05 09:28:22 | requestFromPeer - {"ip":"47.91.218.198","port":4100,"errors":35,"status":"ETIMEOUT","delay":0}
[dbg] 2018-03-05 09:28:23 | Blockchain state - {"date":"2018-03-05T09:24:18.921Z","secondsAgo":245,"stale":true,"rebuild":false,"height":1}
[trc] 2018-03-05 09:28:27 | requestFromPeer - {"ip":"116.85.49.217","port":4100,"errors":32,"status":"ETIMEOUT","delay":0}
[dbg] 2018-03-05 09:28:28 | Removing from memory blockchain blocks with height under - -199
[dbg] 2018-03-05 09:28:31 | Blockchain state - {"date":"2018-03-05T09:24:18.921Z","secondsAgo":253,"stale":true,"rebuild":false,"height":1}
[trc] 2018-03-05 09:28:32 | requestFromPeer - {"ip":"47.91.218.198","port":4100,"errors":36,"status":"ETIMEOUT","delay":0}
[dbg] 2018-03-05 09:28:37 | peers validation error  - ETIMEOUT Request failed GET http://47.91.218.198:4100/peer/list
[dbg] 2018-03-05 09:28:38 | Removing from memory blockchain blocks with height under - -199
[dbg] 2018-03-05 09:28:39 | Blockchain state - {"date":"2018-03-05T09:24:18.921Z","secondsAgo":261,"stale":true,"rebuild":false,"height":1}
[dbg] 2018-03-05 09:28:47 | Blockchain state - {"date":"2018-03-05T09:24:18.921Z","secondsAgo":269,"stale":true,"rebuild":false,"height":1}
[dbg] 2018-03-05 09:28:48 | Removing from memory blockchain blocks with height under - -199
[dbg] 2018-03-05 09:28:55 | Blockchain state - {"date":"2018-03-05T09:24:18.921Z","secondsAgo":277,"stale":true,"rebuild":false,"height":1}
[dbg] 2018-03-05 09:28:58 | Removing from memory blockchain blocks with height under - -199
[dbg] 2018-03-05 09:29:03 | Blockchain state - {"date":"2018-03-05T09:24:18.921Z","secondsAgo":285,"stale":true,"rebuild":false,"height":1}
[dbg] 2018-03-05 09:29:08 | Removing from memory blockchain blocks with height under - -199
[dbg] 2018-03-05 09:29:11 | Blockchain state - {"date":"2018-03-05T09:24:18.921Z","secondsAgo":293,"stale":true,"rebuild":false,"height":1}
[dbg] 2018-03-05 09:29:18 | Removing from memory blockchain blocks with height under - -199
[dbg] 2018-03-05 09:29:19 | Blockchain state - {"date":"2018-03-05T09:24:18.921Z","secondsAgo":301,"stale":true,"rebuild":false,"height":1}
[dbg] 2018-03-05 09:29:27 | Blockchain state - {"date":"2018-03-05T09:24:18.921Z","secondsAgo":309,"stale":true,"rebuild":false,"height":1}

**Comment by faustbrian** [comment]
As Core 2.0 is under development we will close all the PRs and Issues regarding Core 1.0 and only handle critical issues if any come up.
