### ISSUE TITLE
Error when npm install 

### ISSUE THREAD

**Issue by viliamvolosv** [ArkEcosystem/ark-node#65]
error: pathspec 'newtestnet' did not match any file(s) known to git.

  "dependencies": {
    "arkjs": "https://github.com/arkecosystem/ark-js#newtestnet",

is this right link ?

**Comment by ghost** [comment]
Had the same issue. 

I switched to the development branch with `git checkout development` and then did `node install'.

**Comment by faustbrian** [comment]
As Core 2.0 is under development we will close all the PRs and Issues regarding Core 1.0 and only handle critical issues if any come up.
