### ISSUE TITLE
ARKcommander.sh

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-node#8]
Hi,

I believe you have a typo in the "ARKcommander.sh" script. The URL "https://texplorer.ark.io/current" should be "https://explorer.ark.io/current".

**Comment by Doweig** [comment]
Opened a new repo just for you: https://github.com/ArkEcosystem/ark-commander/issues
Can you move your issue there?

**Comment by zillionn** [comment]
This issue was moved to ArkEcosystem/ark-commander#1
