### ISSUE TITLE
Add support other Unix Sheel ( tcsh ) 

### ISSUE THREAD

**Issue by EvertonMelo** [ArkEcosystem/ark-node#98]
add support tee-see-shell on FreeBSD. 

The Port for FreeBSD is Roadmap?

**Comment by faustbrian** [comment]
New features or additions won't be added to ark-node as all focus is on https://github.com/ArkEcosystem/core to move forward.

**Comment by EvertonMelo** [comment]
@faustbrian 

I undestand, thank you for your information.
